M48
; DRILL file {KiCad 9.0.4} date 2025-10-30T13:03:16-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-30T13:03:16-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X121.112Y-64.41
X121.112Y-70.19
T2
X87.0Y-36.0
X87.0Y-75.0
X123.0Y-36.0
X123.0Y-75.0
M30
