void InitalizeEEPROM();
int get_Wifi_eeprom();
void set_Wifi_eeprom(int value);
int get_Wifi_number();
void set_Wifi_number(int number);
int get_Story_Location();
void set_Story_Location(int number);
int get_Room_Number();
void set_Room_Number(int number);
void LastTimeOnDragonBallZ();
void set_Siren_Count(int number);
int get_Siren_Count();
int get_Boot_Presses();
void set_Boot_Presses(int number);
int get_Boss_status();
void set_Boss_status(int number);
void resetAllGameData();