M48
; DRILL file {KiCad (6.0.11)} date Fri 07 Apr 2023 02:31:06 PM CDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-07T14:31:06-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0630
%
G90
G05
T1
X5.0988Y-5.8509
X5.3264Y-5.8509
T2
X7.1811Y-2.2835
X7.2992Y-2.2835
T3
X7.8725Y-2.3305
X8.0396Y-2.4976
T0
M30
